AWSTemplateFormatVersion: '2010-09-09'
Description: QualysPatchingTestingEnvironment

Resources:

  RHEL7Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-00dc9dd6e6540b6e6'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
            sudo systemctl start amazon-ssm-agent
            sudo systemctl enable amazon-ssm-agent
            sudo yum install -y amazon-cloudwatch-agent
            echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
            echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
            sudo systemctl restart sshd
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'RHEL7-Qualys-test'
          
  RHEL8Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-014b7a0df28d143d0'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
            sudo systemctl start amazon-ssm-agent
            sudo systemctl enable amazon-ssm-agent
            sudo yum install -y amazon-cloudwatch-agent
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'RHEL8-Qualys-test'

  RHEL9Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0db3d4b20df92cda7'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
            sudo systemctl start amazon-ssm-agent
            sudo systemctl enable amazon-ssm-agent
            sudo yum install -y amazon-cloudwatch-agent
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'RHEL9-Qualys-test'

  AL2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0e9906f3372e2ca34'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo systemctl start amazon-ssm-agent
            sudo systemctl enable amazon-ssm-agent
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'AL2-Qualys-test'

  AL2023InstanceID:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0c9fcff1fa5c6c6be'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo systemctl start amazon-ssm-agent
            sudo systemctl enable amazon-ssm-agent
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'AL2023-Qualys-test'

  Ubuntu2004Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0a670b8356c1161d6'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
            sudo dpkg -i amazon-ssm-agent.deb
            sudo systemctl start amazon-ssm-agent
            sudo systemctl enable amazon-ssm-agent
            echo "PasswordAuthentication no" >> /etc/ssh/sshd_config
            echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
            sudo systemctl restart sshd
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'Ubuntu2004-Qualys-test'
  
  Windows2019Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0da968818da22c093'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'Windows2019-Qualys-test'

  Windows2022Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-022b2ab17f11c2a2b'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'Windows2022-Qualys-test'

Outputs:
  RHEL7InstanceID:
    Description: "Instance ID for RHEL 7"
    Value: !Ref RHEL7Instance

  RHEL8InstanceID:
    Description: "Instance ID for RHEL 8"
    Value: !Ref RHEL8Instance

  RHEL9InstanceID:
    Description: "Instance ID for RHEL 9"
    Value: !Ref RHEL9Instance
  
  AL2InstanceID:
    Description: "Instance ID for Amazon Linux 2"
    Value: !Ref AL2Instance

  AL2023InstanceID:
    Description: "Instance ID for Amazon Linux 2 2023"
    Value: !Ref AL2023InstanceID

  Ubuntu2004InstanceID:
    Description: "Instance ID for Ubuntu 20.04"
    Value: !Ref Ubuntu2004Instance
  
  Windows2019InstanceID:
    Description: "Instance ID for Windows 2019"
    Value: !Ref Windows2019Instance

  Windows2022InstanceID:
    Description: "Instance ID for Windows 2022"
    Value: !Ref Windows2022Instance