AWSTemplateFormatVersion: '2010-09-09'
Description: QualysPatchingTestingEnvironment

Resources:

  RHEL7Tooled:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0d41ce0bae1bfed4e'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'RHEL7-RCM-Tooled'
          
  RHEL8Tooled:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0cd72765dfee93b70'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'RHEL8-RCM-Tooled'

  RHEL9Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-06d7aa002b2e3009b'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
            sudo systemctl start amazon-ssm-agent
            sudo systemctl enable amazon-ssm-agent
            sudo yum install -y amazon-cloudwatch-agent
            curl -o /tmp/bigfix-installer.sh "https://bftxmgmt-20200710.s3-us-west-2.amazonaws.com/prod-bigfix-installer.sh" 
            sudo bash /tmp/bigfix-installer.sh
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'RHEL9-Qualys-test'

  AL2Tooled:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0aefbb17caf9d2c8e'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'AL2-RCM-Tooled'

  Ubuntu2004Tooled:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0caa4a4ebf5d94780'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'Ubuntu2004-RCM-Tooled'
  
  Windows2019Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0452df044fdac3aa0'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'Windows2019-Qualys-test'

  Windows2022Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0df5c32cf0487ab5b'
      InstanceType: 't3.micro'
      KeyName: 'Todd-SSH-Key'
      IamInstanceProfile: 'AmazonSSMRoleForInstancesQuickSetup'
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: 'subnet-07eadcb4a8af5c510'
        AssociatePublicIpAddress: 'false'
        GroupSet:
          - 'sg-067bc1c22f410ead3'
      Tags:
        - Key: 'Name'
          Value: 'Windows2022-Qualys-test'

Outputs:
  RHEL7TooledID:
    Description: "Instance ID for RHEL 7"
    Value: !Ref RHEL7Tooled

  RHEL8TooledID:
    Description: "Instance ID for RHEL 8"
    Value: !Ref RHEL8Tooled

  RHEL9InstanceID:
    Description: "Instance ID for RHEL 9"
    Value: !Ref RHEL9Instance
  
  AL2TooledID:
    Description: "Instance ID for Amazon Linux 2"
    Value: !Ref AL2Tooled

  Ubuntu2004TooledID:
    Description: "Instance ID for Ubuntu 20.04"
    Value: !Ref Ubuntu2004Tooled
  
  Windows2019InstanceID:
    Description: "Instance ID for Windows 2019"
    Value: !Ref Windows2019Instance

  Windows2022InstanceID:
    Description: "Instance ID for Windows 2022"
    Value: !Ref Windows2022Instance
